apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - image: gcr.io/analisis2/miapiproducts:v1
        name: product-service
        ports:
        - containerPort: 80
          name: product-service       